version: "3.7"

services:
  restservice:
    build: 
      context: .
      dockerfile : restservice.dockerfile
    ports:
      - "8082:8082"
    networks: 
      - isolated_nw2
    volumes: 
      - /tmp
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    ports:
      - "5432:5432"
    networks: 
      - isolated_nw2
    environment:
      POSTGRES_DB : postgres
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : riovas
networks:
  isolated_nw2:
    driver: bridge